### ISSUE TITLE
All files should have a consistent header and use C++ comments

### ISSUE THREAD

**Issue by perlun** [chaos4ever/chaos#2]
- The header should not refer to the GPL, since chaos is no longer licensed under the GNU GPL. The same with libraries; the LGPL header should be removed for these.
- The copyright lines should include the following (unless for files that was actually started earlier; we have a few that goes back to 1997...). We use a single year for simplicity, to avoid having to touch each file every year just for the sake of it.

``` c
// © Copyright 1999 chaos development
```
- All C comments should be changed to C++ comments. (**Note**: Only the comments, we still keep the files as `.c` to avoid messing things up too much. We do not start using C++ constructs, even though the `auto` keyword is a bit tempting.)
- The `int foo (int bar)` style should be updated to use `int foo(int bar)` instead. (i.e. remove the extra space.)
- 80 characters per line should be updated to ~132~ 100, since the screen resolutions are much wider these days. (We originally said 132 but it's unnecessarily high - and you don't necessarily run your editor in full screen anyway.)
- 4 spaces instead of 2 should be used globally.
- ~We should consider using C99 int types (`inttypes.h`/`stdint.h`) instead of "rolling our own".~ Fixed in #86

Of course, this is a bit of work but it makes the codebase more prepared and ready for what's hopefully coming up next (if @johannesl finds the time and energy to do it :smile:). I will start the work with updating storm; we can then update the rest as we please. 

-----

Progress status:

## storm
- [x] generic: fixed in a8d30670b63b89cf13af3bc5340733d63fe7c3b6, except for the following files:
  - [ ] memory.c
- [ ] x86: fixed in a8d30670b63b89cf13af3bc5340733d63fe7c3b6 and dbc060c4bdc3f99f26302ad9b82e406dabb5b03d, but some files remaining.
  - [ ] arguments.c
  - [ ] cpuid.c
  - [ ] dma.c
  - [ ] idt.c
  - [ ] irq.c
  - [ ] memory_physical.c
  - [x] memory_virtual.c. Fixed in 0bcbda5.
  - [ ] process.c
  - [x] thread.c
  - [ ] time.c
  - [ ] timer.c
- [x] raspberrypi: Done right from the start, in #87 and #88.

## libraries
- [x] ~checksum~: Removed in 537d504.
- [x] console: fixed in 32c9dd62828ec41ef708f9722daee53cdd9bb50e
- [x] execute_elf: partially fixed in #86, the rest fixed in #114.
- [x] file: fixed in b966b7b87e5fded1fb6bf234c6116bc5293f7933
- [x] ipc: fixed in b3f04f9a053b065f055d530a70a27ef636cf6ac7 and #98.
- [x] ipv4: fixed in 8512c130e9f5b24e1fde7e303c140a0eb45e4f4a and #86.
- [x] ~ipv6~ Removed in dca316bc45866cdcc86b703c5486df87d1ba266e
- [x] list: fixed in e97f216102e18808fe4607a4856b9dc150f99fd3
- [X] log: fixed in 823f998
- [x] ~math~ Removed in #93
- [ ] memory: partially fixed in #86
- [ ] mutex: partially fixed in e67d6369cb9b199a48b7d767adbc53e629ca2bc7.
- [x] ~network~ Removed in #94
- [x] pci: fixed in 4282b2dbf3fb28345227e2c51982fb264376edd0 and eefbc7ae89be3067fd5cdc88e2fa0d4412a18993
- [ ] posix: ?
- [ ] random: ?
- [ ] serial: ?
- [ ] sound: ?
- [x] string: fixed in #92
- [ ] system: ?
- [ ] time: ?
- [ ] unicode: ?
- [ ] video: ?

## servers
- [ ] servers/block/ata
- [ ] servers/file_system/kernelfs
- [ ] servers/file_system/servicefs
- [ ] servers/sound/soundblaster
- [ ] servers/other/serial
- [ ] servers/tornado
