### ISSUE TITLE
Make chaos bootable again

### ISSUE THREAD

**Issue by perlun** [chaos4ever/chaos#31]
This is an "umbrella issue" to try and enlist all the issues that are currently known. The list will be updated as we go along.

- [x] Generic issues making it hard to boot the system: #10, #12, #14, #21, #25
- [x] The vga server could not be started (various issues): #9, #11
- [x] The console server could not be started.
- [x] Make the keyboard server work again: #32
- [x] Make the boot server work again: #33
- [x] Make the VFS server work again: #34 
- [x] Make the initial_ramdisk server work again: #35, #36, #37
- [x] Make the FAT server work again: #38
- [x] Make cluido work again: #41, #42

**Comment by perlun** [comment]
The system is now bootable, but a bunch of servers are not compilable at the moment. We close this one now and maybe open a new one for 0.0.3.
